apiVersion: v1
kind: Pod
metadata:
  name: portal
  labels:
    app: portal
spec:
  containers:
  - name: portal-container
    image: aluracursos/portal-noticias:1
    ports:
      - containerPort: 80